
[bell]
animation = "EaseOutCirc"
color = "0x464d6a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

#[colors.bright]
#black = "0x625e4c"
#red = "0xf4005f"
#green = "0x98e024"
#yellow = "0xe0d561"
#blue = "0x9d65ff"
#magenta = "0xf4005f"
#cyan = "0x58d1eb"
#white = "0xf6f6ef"

#[colors.normal]
#black = "0x1a1a1a"
#red = "0xf4005f"
#green = "0x98e024"
#yellow = "0xfa8419"
#blue = "0x9d65ff"
#magenta = "0xf4005f"
#cyan = "0x58d1eb"
#white = "0xc4c5b5"

[colors.primary]
background = "0x000000"
foreground = "0xFFFFFF"

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12

[font.bold]
family = "Fira Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 500
multiplier = 1

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
working_directory = "None"
